// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  specsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate sidebar for the specs directory
    },
  ],
};

module.exports = sidebars;