module.exports = {
  source: {
    include: [
      'src/',                    // Frontend source files
      'backend/',               // Backend API files
      'components/',            // Component files
      'docs/'                   // Documentation files
    ],
    exclude: [
      'node_modules/',          // Exclude dependencies
      'dist/',                  // Exclude build output
      'build/',                 // Exclude build output
      'coverage/',              // Exclude test coverage
      'scripts/',               // Exclude script files
      'spec-files/'             // Exclude spec files (to avoid circular generation)
    ],
    includePattern: '.+\\.(js|jsx|ts|tsx|json|py|md)?$',
    excludePattern: '(^|\\/|\\\\)_'
  },
  opts: {
    destination: './specs/',     // Output directory for generated specs
    recurse: true,               // Recursively scan directories
    verbose: true,               // Show detailed output
    encoding: 'utf8',            // Source file encoding
    template: './node_modules/minami' // Template for generated docs
  },
  plugins: [
    'plugins/markdown',          // Parse markdown in comments
    'plugins/summarize',         // Generate summaries
    'plugins/advanced-types'     // Handle complex TypeScript types
  ],
  templates: {
    cleverLinks: true,
    monospaceLinks: false,
    default: {
      outputSourceFiles: true,
      includeDate: false,
      systemName: 'Physical AI & Humanoid Robotics',
      footer: 'Generated by Speckit + Docusaurus',
      copyright: 'Copyright 2025',
      linenums: true
    }
  }
};